services:
  - type: web
    name: inframindtech
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DATABASE_URL
        fromDatabase:
          name: inframindtech-db
          property: connectionString

databases:
  - name: inframindtech-db
    plan: free
